DROP TABLE IF EXISTS cats; 
CREATE TABLE cats ( 
	id INT AUTO_INCREMENT PRIMARY KEY,
	litter_id INT FOREIGN KEY REFERENCES litters(id)
); 
DROP TABLE IF EXISTS litters; 
CREATE TABLE litters ( 
	id INT AUTO_INCREMENT PRIMARY KEY  
); 
DROP TABLE IF EXISTS users; 
CREATE TABLE users ( 
	id INT AUTO_INCREMENT PRIMARY KEY  
); 
DROP TABLE IF EXISTS fosters; 
CREATE TABLE fosters ( 
	id INT AUTO_INCREMENT PRIMARY KEY  
); 
